### ISSUE TITLE
Protections are never respected

### ISSUE THREAD

**Issue by taikedz** [NPXcoot/nssm#18]
Hi guys

Big problem here - mobs, rainbow satf, fire sword etc don't do any checks for protection.... The server spawn is a clusterflop of nyancats and rainbows now, and the lava titan and mese dragon have completely ruined several areas

I've tried to push protection checks before, but it seems they have been lost since the update to 3.0....

Can you *please* code these things with consideration for protection....? Even helps in *singleplayer* mode too to prevent mob griefing, which really is a pain without the protection checks....

Thanks

**Comment by NPXcoot** [comment]
We've added some checks, please test and report if you still have problems.
In the past I removed some of your protection checks because I had errors with them...

**Comment by taikedz** [comment]
Hi NPX

Thanks, will test it as soon as I can. For now I am still trying to figure out the best way to fix the game server..... I fear it might be beyond salvation though...

**Comment by taikedz** [comment]
I never did manage to fix the server. So I've reloaded a new map... ah well. Will do some code combing later to ensure protection works as expected, and push code if needs be...
