### ISSUE TITLE
Mobs destroy protected areas.

### ISSUE THREAD

**Issue by tenplus1** [NPXcoot/nssm#3]
An amazing and potentially dangerous mod in that the monsters within do not honor protected areas and cut through everything in their path...  Many builds were lost in this battle and I urge the writers to check for protection in future battles :)

**Comment by Cat5TV** [comment]
Yeah this was brutal. Installed the mod on our server to test it and it destroyed a bunch of protected builds: a 3-headed bird spawned INSIDE a wooden house and burnt it to the ground with its fire breath. Really would love to see this mod honor protected areas.

**Comment by NPXcoot** [comment]
I promise I'm going to work on it in the future, at the moment I don't have much time, so the development is proceeding slowly...

**Comment by NPXcoot** [comment]
Fixed in master, I hope I have inserted all the necessary controls. Tell us if you still have some problem
