### ISSUE TITLE
Unable to load .png textures

### ISSUE THREAD

**Issue by amianthoidal** [NPXcoot/nssm#4]
I've gotten a few errors in the log such as:

2016-04-25 21:56:30: WARNING[Main]: Irrlicht: Could not open file of texture: nathan.png

It seems the mesh files are trying to call .png textures they do not have access to. If I were not so new to GitHub I would do a pull request but I am not that skilled yet. The solution I used was navigating to the meshes folder and running:

sed -i 's/TextureFilename {.*}//g' *
(run at your own risk! I don't really know what I'm doing!)

in order to remove all lines attempting to load textures from that directory. You can see an example in bloco.x at line 1379.

**Comment by NPXcoot** [comment]
It is a problem in the exportation of the model, I had exported too much elements, i think that is related to the materials, I will solve it exporting again all the models without these useless information... 
Thank you

**Comment by amianthoidal** [comment]
After more testing I think this issue doesn't affect anything. It's just an error message. The mobs spawn properly and the textures seem to be applied correctly.

Thanks for the cool mod!

**Comment by NPXcoot** [comment]
Fixed in master, please tell us if you still have this problem
